spring.application.name=product
spring.jackson.default-property-inclusion=non_null

#=== Conexión Alloy DB QA === #
spring.r2dbc.url=r2dbc:postgresql://dpg-d1q1f23uibrs73e8pss0-a.virginia-postgres.render.com:5432/inventory_product?ssl=true&sslmode=require
spring.r2dbc.username=leomotta
spring.r2dbc.password=rqhFUoLLIl71bYvbznJvIBvnSkMbsFhk
spring.r2dbc.pool.initial-size=2
spring.r2dbc.pool.max-size=10
spring.r2dbc.pool.max-acquire-time=45s
spring.r2dbc.pool.max-idle-time=15m

function.save.product=SELECT * FROM insert_fruit($1::jsonb)
function.find.product=SELECT * FROM find_fruit(:id)